/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaderboardSlugRouteImport } from './routes/leaderboard.$slug'
import { Route as LangSlugRouteImport } from './routes/lang.$slug'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as OauthGithubReturnRouteImport } from './routes/oauth.github.return'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardSlugRoute = LeaderboardSlugRouteImport.update({
  id: '/leaderboard/$slug',
  path: '/leaderboard/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSlugRoute = LangSlugRouteImport.update({
  id: '/lang/$slug',
  path: '/lang/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGithubReturnRoute = OauthGithubReturnRouteImport.update({
  id: '/oauth/github/return',
  path: '/oauth/github/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/lang/$slug': typeof LangSlugRoute
  '/leaderboard/$slug': typeof LeaderboardSlugRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/lang/$slug': typeof LangSlugRoute
  '/leaderboard/$slug': typeof LeaderboardSlugRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/lang/$slug': typeof LangSlugRoute
  '/leaderboard/$slug': typeof LeaderboardSlugRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/lang/$slug'
    | '/leaderboard/$slug'
    | '/oauth/github/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/lang/$slug'
    | '/leaderboard/$slug'
    | '/oauth/github/return'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/lang/$slug'
    | '/leaderboard/$slug'
    | '/oauth/github/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  LangSlugRoute: typeof LangSlugRoute
  LeaderboardSlugRoute: typeof LeaderboardSlugRoute
  OauthGithubReturnRoute: typeof OauthGithubReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/$slug': {
      id: '/leaderboard/$slug'
      path: '/leaderboard/$slug'
      fullPath: '/leaderboard/$slug'
      preLoaderRoute: typeof LeaderboardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lang/$slug': {
      id: '/lang/$slug'
      path: '/lang/$slug'
      fullPath: '/lang/$slug'
      preLoaderRoute: typeof LangSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/github/return': {
      id: '/oauth/github/return'
      path: '/oauth/github/return'
      fullPath: '/oauth/github/return'
      preLoaderRoute: typeof OauthGithubReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  LangSlugRoute: LangSlugRoute,
  LeaderboardSlugRoute: LeaderboardSlugRoute,
  OauthGithubReturnRoute: OauthGithubReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
